<a href="https://colab.research.google.com/github/Gopikanta/Natural-Language-Processing---LAB/blob/main/LAB_Natural_Language_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install PyPDF2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 7.8 MB/s eta 0:00:00


In [ ]:
!pip install --upgrade PyPDF2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 5.6 MB/s eta 0:00:00


In [ ]:
### NLP program no: 1
# Read a PDF file and print its first page.

import PyPDF2
from PyPDF2 import PdfReader
from PyPDF2 import PdfWriter

pdffile = PdfReader("samplepage.pdf")
pagecount = len(pdffile.pages)
print(f"\nPdf Page Length - {pagecount}")
page1 = pdffile.pages[0]
text1 = page1.extract_text()
print("\nText Contents Of Page 1 >> \n")
print(text1)
print('\nSaving As "Result.pdf" ')
pdfresult = page1



Pdf Page Length - 2

Text Contents Of Page 1 >> 

 A Simple PDF File 
 This is a small demonstration .pdf file - 
 just for use in the Virtual Mechanics tutorials. More text. And more 
 text. And more text. And more text. And more text. 
 And more text. And more text. And more text. And more text. And more 
 text. And more text. Boring, zzzzz. And more text. And more text. And 
 more text. And more text. And more text. And more text. And more text. 
 And more text. And more text. 
 And more text. And more text. And more text. And more text. And more 
 text. And more text. And more text. Even more. Continued on page 2 ...

Saving As "Result.pdf" 


In [ ]:
!pip install nltk

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
### NLP Program no : 2
# Word to token .

import nltk
nltk.download('punkt')

# Tokenize the sentence
file = open("Alice.txt")
sentence = file.read()
tokens = nltk.word_tokenize(sentence)
print("Tokens:", tokens)

Tokens: ['Alice', 'was', 'beginning', 'to', 'get', 'very', 'tired', 'of', 'sitting', 'by', 'her', 'sister', 'on', 'the', 'bank', ',', 'and', 'of', 'having', 'nothing', 'to', 'do', ':', 'once', 'or', 'twice', 'she', 'had', 'peeped', 'into', 'the', 'book', 'her', 'sister', 'was', 'reading', ',', 'but', 'it', 'had', 'no', 'pictures', 'or', 'conversations', 'in', 'it', ',', "'and", 'what', 'is', 'the', 'use', 'of', 'a', 'book', ',', "'", 'thought', 'Alice', 'without', 'picure', 'or', 'conversation', "'"]


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
### NLP Program no: 3
# Remove stopwords from a string.

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt')

file = open("Alice.txt")
sentence = file.read()
stop_words = set(stopwords.words('english'))
words = word_tokenize(sentence)

filtered_words = [word for word in words if word.lower() not in stop_words]
cleaned_text = ' '.join(filtered_words)
print("Original Text:")
print(sentence)

print("\nCleaned Text (without stopwords):")
print(cleaned_text)

Original Text:
Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the  book her sister was reading , but it had no pictures or conversations in it, 'and what is the use of a book, ' thought Alice without picure or conversation'

Cleaned Text (without stopwords):
Alice beginning get tired sitting sister bank , nothing : twice peeped book sister reading , pictures conversations , 'and use book , ' thought Alice without picure conversation '


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
### NLP Program no: 4

# >> Convert text Data into lowercase:

input_txt = open("Alice.txt")
output_txt = input_txt.read()
lowercased_txt = output_txt.lower()
print("Text in lowercase:", lowercased_txt)

Text in lowercase: alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the  book her sister was reading , but it had no pictures or conversations in it, 'and what is the use of a book, ' thought alice without picure or conversation'


In [ ]:
### NLP progran no: 5

# >> Remove Punctuations.

import string

input_txt = open("Alice.txt")
output_txt = input_txt.read()


# Create a translation table to remove punctuation characters
translator = str.maketrans('', '', string.punctuation)

# Use the translate method to remove punctuations from the sentence
cleaned_sentence = output_txt.translate(translator)

print("Sentence without punctuations:", cleaned_sentence)

Sentence without punctuations: Alice was beginning to get very tired of sitting by her sister on the bank and of having nothing to do once or twice she had peeped into the  book her sister was reading  but it had no pictures or conversations in it and what is the use of a book  thought Alice without picure or conversation


In [ ]:
### NLP Program no : 6

# >>  Frequency of words.

input_txt = open("Alice.txt")
output_txt = input_txt.read()
words = output_txt.split()
words = [word.strip(".,!?\"'(){}[]") for word in words]

word_freq = {}
for word in words:
    word = word.lower()
    if word:
        word_freq[word] = word_freq.get(word, 0) + 1

print("Word Frequencies:")
for word, freq in word_freq.items():
    print(f"{word}: {freq}")

Word Frequencies:
alice: 2
was: 2
beginning: 1
to: 2
get: 1
very: 1
tired: 1
of: 3
sitting: 1
by: 1
her: 2
sister: 2
on: 1
the: 3
bank: 1
and: 2
having: 1
nothing: 1
do:: 1
once: 1
or: 3
twice: 1
she: 1
had: 2
peeped: 1
into: 1
book: 2
reading: 1
but: 1
it: 2
no: 1
pictures: 1
conversations: 1
in: 1
what: 1
is: 1
use: 1
a: 1
thought: 1
without: 1
picure: 1
conversation: 1


In [ ]:
### NLP Program no : 7

## Extract Entity from a text

import spacy

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Get input text from the user
input_txt = open('Alice.txt')
output_txt = input_txt.read()

# Process the input text with spaCy
doc = nlp(output_txt)

# Extract entities and print them
entities = [(ent.text, ent.label_) for ent in doc.ents]

if entities:
    print("Entities:")
    for entity, label in entities:
        print(f"{entity} - {label}")
else:
    print("No entities found.")





Entities:
Alice - PERSON
Alice - PERSON


In [ ]:
### NLP Program no : 8

## Custom Lookup Dictionary and Create a customer Function for text Standardization.

lookup_dict = {
    "u": "you",
    "ur": "your",
    "gr8": "great",
    "btw": "by the way",
    "lol": "laugh out loud",
    "omg": "oh my god",
    # Add more custom mappings as needed
}


def standardize_text(text):
    words = text.split()
    standardized_text = []

    for word in words:
        standardized_word = lookup_dict.get(word.lower(), word)
        standardized_text.append(standardized_word)

    return " ".join(standardized_text)


text = "u should check this out, btw it's gr8!"
standardized_text = standardize_text(text)
print("Original Text:", text)
print("Standardized Text:", standardized_text)



Original Text: u should check this out, btw it's gr8!
Standardized Text: you should check this out, by the way it's gr8!


In [ ]:
!pip install autocorrect


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 622.8/622.8 kB 12.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for autocorrect: filename=autocorrect-2.6.1-py3-none-any.whl size=622363 sha256=b81794dc8f0f6af15bfc8bca9ec837360d2c83c59bf8c4d1a7f161c626e437c9
  Stored in directory: /root/.cache/pip/wheels/b5/7b/6d/b76b29ce11ff8e2521c8c7dd0e5bfee4fb1789d76193124343
Successfully built autocorrect


In [ ]:
### NLP Program no: 9

# >> Spelling mistake.

from autocorrect import Speller

spell = Speller()

error_words = ['samlpe', 'corertc', 'cmoment', 'lodaing']

for word in error_words:
  corrected_word = spell(word)
  print(f"{word} - > {corrected_word}")

samlpe - > sample
corertc - > correct
cmoment - > comment
lodaing - > loading


In [ ]:
### NLP Program no: 10

# >> 10. Perform steaming and levetization on Text.

import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

# Download NLTK data if not already downloaded
nltk.download('punkt')
nltk.download('wordnet')

input_txt = open("Alice.txt")
output_txt = input_txt.read()


# Perform stemming
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in word_tokenize(output_txt)]
stemmed_text = ' '.join(stemmed_words)
print("Stemmed text:")
print(stemmed_text)

# Perform lemmatization
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in word_tokenize(output_txt)]
lemmatized_text = ' '.join(lemmatized_words)
print("\nLemmatized text:")
print(lemmatized_text)








[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


Stemmed text:
alic wa begin to get veri tire of sit by her sister on the bank , and of have noth to do : onc or twice she had peep into the book her sister wa read , but it had no pictur or convers in it , 'and what is the use of a book , ' thought alic without picur or convers '

Lemmatized text:
Alice wa beginning to get very tired of sitting by her sister on the bank , and of having nothing to do : once or twice she had peeped into the book her sister wa reading , but it had no picture or conversation in it , 'and what is the use of a book , ' thought Alice without picure or conversation '


In [ ]:
### NLP Program no: 11

# N - Gram

input_text = "This is a sample text for generating n-grams"
n = 3

words = input_text.split()
ngrams = []

for i in range(len(words) - n + 1):
    ngrams.append(" ".join(words[i:i + n]))

for ngram in ngrams:
    print(ngram)

This is a
is a sample
a sample text
sample text for
text for generating
for generating n-grams


In [ ]:
### NLP Program no : 12

# >> Convert text features using one hot Encoding

from sklearn.preprocessing import OneHotEncoder

# Sample text features as a list of categorical values
text_features = ['This is the first picture. ','This is the second picture. ','This is the third picture. ','This is the forth picture. ','Is this  the  first picture ?']

# Create a OneHotEncoder object
encoder = OneHotEncoder()

# Reshape the text_features array into a 2D array (required by the encoder)
text_features_reshaped = [[feature] for feature in text_features]

# Fit and transform the text_features to obtain the one-hot encoded representation
one_hot_encoded_features = encoder.fit_transform(text_features_reshaped).toarray()

# Print the one-hot encoded features
print("One-hot encoded features:")
for feature, encoding in zip(text_features, one_hot_encoded_features):
    print(f"{feature}: {encoding}")

One-hot encoded features:
This is the first picture. : [0. 1. 0. 0. 0.]
This is the second picture. : [0. 0. 0. 1. 0.]
This is the third picture. : [0. 0. 0. 0. 1.]
This is the forth picture. : [0. 0. 1. 0. 0.]
Is this  the  first picture ?: [1. 0. 0. 0. 0.]


In [ ]:
### NLP Program no : 13

# >> Convert text Features using a count vectoriser.

from sklearn.feature_extraction.text import CountVectorizer
text_data = [
    "This is the first sentence.",
    "And this is the second sentence.",
    "Finally, the third sentence."
]
# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the text data
X = vectorizer.fit_transform(text_data)

# Convert sparse matrix to dense NumPy array
X_dense = X.toarray()

# Print the transformed features
print(X_dense)

[[0 0 1 1 0 1 1 0 1]
 [1 0 0 1 1 1 1 0 1]
 [0 1 0 0 0 1 1 1 0]]


In [ ]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
### NLP Program no : 14

# >> POS Tagging.

import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

# Tokenize the sentence into words
input_sentence = input("Enter a sentence: ")
words = word_tokenize(input_sentence)

# Perform POS tagging
pos_tags = nltk.pos_tag(words)

# Print the POS-tagged output
print(pos_tags)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


Enter a sentence: Kavya is a intelligent girl.
[('Kavya', 'NNP'), ('is', 'VBZ'), ('a', 'DT'), ('intelligent', 'JJ'), ('girl', 'NN'), ('.', '.')]


In [ ]:
### NLP Program no : 15

# >> Word error rate.

import nltk

def word_error_rate(reference, hypothesis):
  reference = nltk.word_tokenize(reference.lower())
  hypothesis = nltk.word_tokenize(hypothesis.lower())
  edit_distance = nltk.edit_distance(reference, hypothesis)
  word_error_rate_score = edit_distance / len(reference)
  return word_error_rate_score
reference =  "She sells seashells by the seashore"
hypothesis =  "He sells seashells by the sea"
word_error_rate_score = word_error_rate(reference, hypothesis)
print("Word error rate : ", word_error_rate_score)

Word error rate :  0.3333333333333333
